/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ModuleWorker.View;

import ModuleWorker.SYSCON;
import ModuleWorker.SYSWALLPCON;
import NCLPM.EVENTS;
import NCLPM.LOG;
import java.awt.Dimension;
import java.io.File;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class JFRPrincipal extends javax.swing.JFrame 
{

    /**
     * Creates new form JFRPrincipal
     */
    
    JFrame form;
    SYSCON sys = new SYSCON();
    LOG lc = new LOG();
    EVENTS evn = new EVENTS();
    public File imagen = new File (System.getProperty ("user.dir")+"\\Fondo.png");

    public JFRPrincipal()
    {
        initComponents();
        image();
        this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setTitle(sys.nombre_sistema()+" - "+sys.nombre_compañia()+" - Versión V"+sys.version());
        
    }
    
    private void image()
    {   
        SYSWALLPCON.cargarImagen(JDEscritorio, imagen);
    }

    //ACTUALIZACION
    public void actualizacion()
    {
        //ARGUMENTOS DE ACTUALIZACION
        System.exit(0);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JDEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMSesion = new javax.swing.JMenu();
        JSMMantenimientoUsuarios = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout JDEscritorioLayout = new javax.swing.GroupLayout(JDEscritorio);
        JDEscritorio.setLayout(JDEscritorioLayout);
        JDEscritorioLayout.setHorizontalGroup(
            JDEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1243, Short.MAX_VALUE)
        );
        JDEscritorioLayout.setVerticalGroup(
            JDEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 651, Short.MAX_VALUE)
        );

        JMSesion.setText("Sesion");

        JSMMantenimientoUsuarios.setText("Mantenimiento de Usuarios");
        JSMMantenimientoUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JSMMantenimientoUsuariosActionPerformed(evt);
            }
        });
        JMSesion.add(JSMMantenimientoUsuarios);

        jMenuBar1.add(JMSesion);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JDEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JDEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JSMMantenimientoUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JSMMantenimientoUsuariosActionPerformed
   
    try 
    {
        JIFMatenerUsuario usuarios = new JIFMatenerUsuario();
        if(JSMMantenimientoUsuarios.getActionCommand().equals("Abierto")){JOptionPane.showMessageDialog(this,"Ya esta abierto");}
        else
        {
            JSMMantenimientoUsuarios.setActionCommand("Abierto");
            JDEscritorio.add(usuarios);
            Dimension desktopSize = JDEscritorio.getSize();
            Dimension FrameSize = usuarios.getSize();
            usuarios.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
            usuarios.show();
        }    
    } 
    catch (Exception e) 
     {
         lc.write("Error intentando abrir 'Mantenimiento Usuarios'", "JFRPrincipal", e.getMessage());
     }
       
    

    }//GEN-LAST:event_JSMMantenimientoUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFRPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFRPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFRPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFRPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new JFRPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane JDEscritorio;
    private javax.swing.JMenu JMSesion;
    private javax.swing.JMenuItem JSMMantenimientoUsuarios;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
