/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ModuleWorker.View;

import ModuleWorker.Core.JOB_Update;
import ModuleWorker.IC.MWCON;
import ModuleWorker.IC.NANOCON_Asistencia;
import ModuleWorker.SYSAUDIOCON;
import ModuleWorker.SYSCON;
import ModuleWorker.SYSControl;
import ModuleWorker.SYSSCHEDULERCON;
import ModuleWorker.SYSWALLPCON;
import NCLPM.EVENTS;
import NCLPM.GEN_STATUS;
import NCLPM.LOG;
import NMOC.MD_Consultar.View.JIFConsultarCertificados;
import NMOC.MD_Consultar.View.JIFConsultarCertificadosVencidos;
import NMOC.MD_Consultar.View.JIFConsultarOrdenesTrabajo;
import NMOC.MD_Generar.View.JIFGenerarCertificado;
import NMOC.MD_Generar.View.JIFGenerarCotizacion;
import NMOC.MD_Generar.View.JIFGenerarOrdenTrabajo;
import NMOC.MD_Mantenimientos.View.JIFMantenerClientes;
import NMOC.MD_Mantenimientos.View.JIFMantenerImplementos;
import NMOC.MD_Mantenimientos.View.JIFMantenerPersonal;
import NMOC.MD_Mantenimientos.View.JIFMantenerProductos;
import NMOC.MD_Ventas.View.JIFRegistroContacto;
import java.awt.Dimension;
import java.io.File;
import java.util.concurrent.TimeUnit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.quartz.SchedulerException;

/**
 *
 * @author USUARIO
 */
public class JFRPrincipal extends javax.swing.JFrame 
{

    /**
     * Creates new form JFRPrincipal
     */
    
    JFrame form;
    SYSCON sys = new SYSCON();
    LOG lc = new LOG();
    EVENTS evn = new EVENTS();
    GEN_STATUS gnst = new GEN_STATUS();
    public File imagen = new File (System.getProperty ("user.dir")+"\\Fondo.png");
    
    public JFRPrincipal() 
    {
        initComponents();        
        image();
        this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
        //TAG VERSIÓN INTERNA DE DESARROLLO
        this.setTitle(sys.nombre_sistema()+" - "+sys.nombre_compañia()+" - Versión V"+sys.version()+" VERSIÓN INTERNA DE DESARROLLO");
        comprobar_actualizaciones();
        //QUITA FUNCIONES
        quitaFunciones();
        
    }
    
    //se agrega metodo para quitar las funcionalidades mencionadas en el correo Fin del Ciclo de Vida Génesis
    private void quitaFunciones()
    {
        JSMRegistrarSalida.setVisible(false);
        String permiso_especial = "ROOT ROOT";
        System.out.println("PERMISO ESPECIAL " +permiso_especial);
        if(permiso_especial.equals("ROOT ROOT"))
        {
            //NOTHING
        }else
        {
            JSMMantenimientoUsuarios.setVisible(false);
            JSMPermisosUsuarios.setVisible(false);
            JSMMantenerPersonal.setVisible(false);
            JSMMantenerProducto.setVisible(false);
            JSMMantenerImplementos.setVisible(false);
            JSMGenerarCotizacion.setVisible(false);
            JMVentas.setVisible(false);
            jMenu4.setVisible(false);
        }
    }
    
    public static void detectar(String ID_PER)
    {
        NANOCON_Asistencia P_ASIST = new NANOCON_Asistencia();
        MWCON mw = new MWCON();

        if(P_ASIST.obtenerEstadoAsistencia(mw.fecha_actual_clasica(), ID_PER).equals("SALIDA"))
        {
            JSMRegistrarSalida.setEnabled(false);
            JSMRegistrarSalida.setText("Salida Registrada");
        }
     
    }
    
    private void image()
    {   
        SYSWALLPCON.cargarImagen(JDEscritorio, imagen);
    }

    private void comprobar_actualizaciones()  
    {
        try 
        {
          SYSSCHEDULERCON SCheduler = new SYSSCHEDULERCON(); //SE ENCARGA DE LAS TAREAS PRE PROGRAMADAs
          SCheduler.Execute_Scheduler(JOB_Update.class, 175);
        } catch (SchedulerException SE) 
          {
            lc.write("Ha ocurrido un error al intentar encender el comprobador de actualizaciones", "JFRPrincipal", SE);
          }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JDEscritorio = new javax.swing.JDesktopPane();
        JTBHerramientas = new javax.swing.JToolBar();
        btnAgregarCliente = new javax.swing.JButton();
        btnAgregarPersonal = new javax.swing.JButton();
        btnGenerarOrden = new javax.swing.JButton();
        btnAdministrarCertificado = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        JMPrincipal = new javax.swing.JMenuBar();
        JMSesion = new javax.swing.JMenu();
        JSMRegistrarSalida = new javax.swing.JMenuItem();
        JSMMantenimientoUsuarios = new javax.swing.JMenuItem();
        JSMPermisosUsuarios = new javax.swing.JMenuItem();
        JSMCerrarSesion = new javax.swing.JMenuItem();
        JMMantenimientos = new javax.swing.JMenu();
        JSMMantenerClientes = new javax.swing.JMenuItem();
        JSMMantenerPersonal = new javax.swing.JMenuItem();
        JSMMantenerProducto = new javax.swing.JMenuItem();
        JSMMantenerImplementos = new javax.swing.JMenuItem();
        JMGenerar = new javax.swing.JMenu();
        JSMGenerarCotizacion = new javax.swing.JMenuItem();
        JSMGenerarOrden = new javax.swing.JMenuItem();
        JSMGenerarCertificado = new javax.swing.JMenuItem();
        JMConsultar = new javax.swing.JMenu();
        JSMConsultarOrden = new javax.swing.JMenuItem();
        JSMConsultarCertificado = new javax.swing.JMenuItem();
        JSMConsultarCertificadoVen = new javax.swing.JMenuItem();
        JMVentas = new javax.swing.JMenu();
        JSMRegistroContactos = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        javax.swing.GroupLayout JDEscritorioLayout = new javax.swing.GroupLayout(JDEscritorio);
        JDEscritorio.setLayout(JDEscritorioLayout);
        JDEscritorioLayout.setHorizontalGroup(
            JDEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1243, Short.MAX_VALUE)
        );
        JDEscritorioLayout.setVerticalGroup(
            JDEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
        );

        JTBHerramientas.setBackground(new java.awt.Color(204, 204, 204));
        JTBHerramientas.setFloatable(false);
        JTBHerramientas.setBorderPainted(false);
        JTBHerramientas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JTBHerramientas.setOpaque(false);

        btnAgregarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NIMG/Client1_add32.png"))); // NOI18N
        btnAgregarCliente.setToolTipText("Agregar Cliente");
        btnAgregarCliente.setFocusable(false);
        btnAgregarCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregarCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        JTBHerramientas.add(btnAgregarCliente);

        btnAgregarPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NIMG/Male_User_add32.png"))); // NOI18N
        btnAgregarPersonal.setToolTipText("Agregar Personal");
        btnAgregarPersonal.setFocusable(false);
        btnAgregarPersonal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregarPersonal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        JTBHerramientas.add(btnAgregarPersonal);

        btnGenerarOrden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NIMG/OrdenV2 32.png"))); // NOI18N
        btnGenerarOrden.setToolTipText("Generar Orden de Servicio");
        btnGenerarOrden.setFocusable(false);
        btnGenerarOrden.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGenerarOrden.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        JTBHerramientas.add(btnGenerarOrden);

        btnAdministrarCertificado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NIMG/CertificadoV232.png"))); // NOI18N
        btnAdministrarCertificado.setToolTipText("Administrar Certificados");
        btnAdministrarCertificado.setFocusable(false);
        btnAdministrarCertificado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdministrarCertificado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        JTBHerramientas.add(btnAdministrarCertificado);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NIMG/codigo-pin32.png"))); // NOI18N
        jButton4.setToolTipText("Generar Codigos");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        JTBHerramientas.add(jButton4);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NIMG/ConsultarOrdenV2 32.png"))); // NOI18N
        jButton5.setToolTipText("Consulta de Ordenes de Servicio");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        JTBHerramientas.add(jButton5);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NIMG/ConsultaCert 32.png"))); // NOI18N
        jButton2.setToolTipText("Consulta de Certificados");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        JTBHerramientas.add(jButton2);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NIMG/logout-icon32.png"))); // NOI18N
        jButton1.setToolTipText("Cerrar Sesión");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        JTBHerramientas.add(jButton1);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 51, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NIMG/Notification_32.png"))); // NOI18N
        jButton3.setText("0");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        JTBHerramientas.add(jButton3);

        JMSesion.setText("Sesion");
        JMSesion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        JSMRegistrarSalida.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        JSMRegistrarSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NIMG/check IN_24px.png"))); // NOI18N
        JSMRegistrarSalida.setText("Registrar Salida");
        JSMRegistrarSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JSMRegistrarSalidaActionPerformed(evt);
            }
        });
        JMSesion.add(JSMRegistrarSalida);

        JSMMantenimientoUsuarios.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        JSMMantenimientoUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NIMG/personal.png"))); // NOI18N
        JSMMantenimientoUsuarios.setText("Mantenimiento de Usuarios");
        JSMMantenimientoUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JSMMantenimientoUsuariosActionPerformed(evt);
            }
        });
        JMSesion.add(JSMMantenimientoUsuarios);

        JSMPermisosUsuarios.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        JSMPermisosUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NIMG/Lock-Unlock-icon.png"))); // NOI18N
        JSMPermisosUsuarios.setText("Permisos de Usuarios");
        JSMPermisosUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JSMPermisosUsuariosActionPerformed(evt);
            }
        });
        JMSesion.add(JSMPermisosUsuarios);

        JSMCerrarSesion.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        JSMCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NIMG/logout-icon24.png"))); // NOI18N
        JSMCerrarSesion.setText("Cerrar Sesión");
        JSMCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JSMCerrarSesionActionPerformed(evt);
            }
        });
        JMSesion.add(JSMCerrarSesion);

        JMPrincipal.add(JMSesion);

        JMMantenimientos.setText("Mantenimientos");
        JMMantenimientos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        JSMMantenerClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        JSMMantenerClientes.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        JSMMantenerClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NIMG/Client1_add24.png"))); // NOI18N
        JSMMantenerClientes.setText("Mantener Clientes");
        JSMMantenerClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JSMMantenerClientesActionPerformed(evt);
            }
        });
        JMMantenimientos.add(JSMMantenerClientes);

        JSMMantenerPersonal.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        JSMMantenerPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NIMG/Male_User_add24.png"))); // NOI18N
        JSMMantenerPersonal.setText("Mantener Personal");
        JSMMantenerPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JSMMantenerPersonalActionPerformed(evt);
            }
        });
        JMMantenimientos.add(JSMMantenerPersonal);

        JSMMantenerProducto.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        JSMMantenerProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NIMG/ProductsV2_24.png"))); // NOI18N
        JSMMantenerProducto.setText("Mantener Producto");
        JSMMantenerProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JSMMantenerProductoActionPerformed(evt);
            }
        });
        JMMantenimientos.add(JSMMantenerProducto);

        JSMMantenerImplementos.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        JSMMantenerImplementos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NIMG/machinesV1.png"))); // NOI18N
        JSMMantenerImplementos.setText("Mantener Implementos");
        JSMMantenerImplementos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JSMMantenerImplementosActionPerformed(evt);
            }
        });
        JMMantenimientos.add(JSMMantenerImplementos);

        JMPrincipal.add(JMMantenimientos);

        JMGenerar.setText("Generar");
        JMGenerar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        JSMGenerarCotizacion.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        JSMGenerarCotizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NIMG/Files-New-File-icon.png"))); // NOI18N
        JSMGenerarCotizacion.setText("Generar Cotización");
        JSMGenerarCotizacion.setEnabled(false);
        JSMGenerarCotizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JSMGenerarCotizacionActionPerformed(evt);
            }
        });
        JMGenerar.add(JSMGenerarCotizacion);

        JSMGenerarOrden.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        JSMGenerarOrden.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        JSMGenerarOrden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NIMG/OrdenV2_1 24.png"))); // NOI18N
        JSMGenerarOrden.setText("Generar Orden Trabajo");
        JSMGenerarOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JSMGenerarOrdenActionPerformed(evt);
            }
        });
        JMGenerar.add(JSMGenerarOrden);

        JSMGenerarCertificado.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        JSMGenerarCertificado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NIMG/CertificadoV224.png"))); // NOI18N
        JSMGenerarCertificado.setText("Generar Certificado");
        JSMGenerarCertificado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JSMGenerarCertificadoActionPerformed(evt);
            }
        });
        JMGenerar.add(JSMGenerarCertificado);

        JMPrincipal.add(JMGenerar);

        JMConsultar.setText("Consultar");
        JMConsultar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        JSMConsultarOrden.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        JSMConsultarOrden.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        JSMConsultarOrden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NIMG/ConsultarOrdenV2 24_1.png"))); // NOI18N
        JSMConsultarOrden.setText("Consultar Orden Trabajo");
        JSMConsultarOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JSMConsultarOrdenActionPerformed(evt);
            }
        });
        JMConsultar.add(JSMConsultarOrden);

        JSMConsultarCertificado.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        JSMConsultarCertificado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NIMG/ConsultaCert 24.png"))); // NOI18N
        JSMConsultarCertificado.setText("Consultar Certificado");
        JSMConsultarCertificado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JSMConsultarCertificadoActionPerformed(evt);
            }
        });
        JMConsultar.add(JSMConsultarCertificado);

        JSMConsultarCertificadoVen.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        JSMConsultarCertificadoVen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NIMG/OutOFDate_ConsultaCert24.png"))); // NOI18N
        JSMConsultarCertificadoVen.setText("Consultar Certificado Vencidos");
        JSMConsultarCertificadoVen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JSMConsultarCertificadoVenActionPerformed(evt);
            }
        });
        JMConsultar.add(JSMConsultarCertificadoVen);

        JMPrincipal.add(JMConsultar);

        JMVentas.setText("Ventas");
        JMVentas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        JSMRegistroContactos.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        JSMRegistroContactos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NIMG/CertificadoV224.png"))); // NOI18N
        JSMRegistroContactos.setText("Registro Contactos");
        JSMRegistroContactos.setEnabled(false);
        JSMRegistroContactos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JSMRegistroContactosActionPerformed(evt);
            }
        });
        JMVentas.add(JSMRegistroContactos);

        JMPrincipal.add(JMVentas);

        jMenu4.setText("Administración");
        jMenu4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JMPrincipal.add(jMenu4);

        setJMenuBar(JMPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JDEscritorio)
            .addComponent(JTBHerramientas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(JTBHerramientas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JDEscritorio))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JSMMantenimientoUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JSMMantenimientoUsuariosActionPerformed
       
        try
        {
            JIFMatenerUsuario usuarios = new JIFMatenerUsuario();
            JFrame jf=new JFrame();
            jf.setAlwaysOnTop(true);

            if(JSMMantenimientoUsuarios.getActionCommand().equals("Abierto"))
                {
                    SYSAUDIOCON sysau = new SYSAUDIOCON();
                    sysau.E_ERROR();
                    JOptionPane.showMessageDialog(jf,"Ya esta abierto", "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
                }
            else
            {                
                JSMMantenimientoUsuarios.setActionCommand("Abierto");
                JDEscritorio.add(usuarios);
                Dimension desktopSize = JDEscritorio.getSize();
                Dimension FrameSize = usuarios.getSize();
                usuarios.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
                evn.write(JMSesion.getText(), "Abrio el formulario 'Mantener Usuario'", "JFPrincipal", "Menu 'Mantener Usuario' Presionado");
                usuarios.show();
            }
        }
        catch (Exception e)
        {
            
            lc.write("Error intentando abrir 'Mantenimiento Usuarios'", "JFRPrincipal", e);
        }

    }//GEN-LAST:event_JSMMantenimientoUsuariosActionPerformed

    private void JSMCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JSMCerrarSesionActionPerformed
        
    try 
    {
      MWCON mw = new MWCON();
      gnst.write_DIS(JMSesion.getText(), mw.hour_actual() , mw.fecha_actual(), "NORMAL");
      new SYSControl().Close_System();
    } catch (Exception sqle) 
        {
           lc.write( "Ha ocurrido algun error al intentar cerrar el sistema!","JFPrincipal metodo JSMCerrar Sesión Linea 255", sqle);
        }

    }//GEN-LAST:event_JSMCerrarSesionActionPerformed

    private void JSMMantenerClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JSMMantenerClientesActionPerformed
        
        try
        {
            JIFMantenerClientes clientes = new JIFMantenerClientes();
            JFrame jf=new JFrame();
            jf.setAlwaysOnTop(true);

            if(JSMMantenerClientes.getActionCommand().equals("Abierto"))
                {
                    SYSAUDIOCON sysau = new SYSAUDIOCON();
                    sysau.E_ERROR();
                    JOptionPane.showMessageDialog(jf,"Ya esta abierto", "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
                }
            else
            {                
                JSMMantenerClientes.setActionCommand("Abierto");
                JDEscritorio.add(clientes);
                Dimension desktopSize = JDEscritorio.getSize();
                Dimension FrameSize = clientes.getSize();
                clientes.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
                evn.write(JMSesion.getText(), "Abrio el formulario 'Mantener Clientes'", "JFPrincipal", "Menu 'Mantener Clientes' Presionado");
                clientes.show();
            }
        }
        catch (Exception e)
        {
            
            lc.write("Error intentando abrir 'Mantenimiento Clientes'", "JFRPrincipal", e);
        }
        
    }//GEN-LAST:event_JSMMantenerClientesActionPerformed

    private void JSMPermisosUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JSMPermisosUsuariosActionPerformed

    try
    {
       JIFPermisos permisos = new JIFPermisos();
       JFrame jf=new JFrame();
       jf.setAlwaysOnTop(true);

       if(JSMPermisosUsuarios.getActionCommand().equals("Abierto"))
           {
               SYSAUDIOCON sysau = new SYSAUDIOCON();
               sysau.E_ERROR();
               JOptionPane.showMessageDialog(jf,"Ya esta abierto", "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
           }
       else
       {                
           JSMPermisosUsuarios.setActionCommand("Abierto");
           JDEscritorio.add(permisos);
           Dimension desktopSize = JDEscritorio.getSize();
           Dimension FrameSize = permisos.getSize();
           permisos.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
           evn.write(JMSesion.getText(), "Abrio el formulario 'Permisos'", "JFPrincipal", "Menu 'Permisos' Presionado");
           permisos.show();
       }
    }
   catch (Exception e)
   {

       lc.write("Error intentando abrir 'Permisos'", "JFRPrincipal", e);
   }

    }//GEN-LAST:event_JSMPermisosUsuariosActionPerformed

    private void JSMMantenerPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JSMMantenerPersonalActionPerformed
        
    try
    {
        JIFMantenerPersonal personal = new JIFMantenerPersonal();
        JFrame jf=new JFrame();
        jf.setAlwaysOnTop(true);

        if(JSMMantenerPersonal.getActionCommand().equals("Abierto"))
            {
                SYSAUDIOCON sysau = new SYSAUDIOCON();
                sysau.E_ERROR();
                JOptionPane.showMessageDialog(jf,"Ya esta abierto", "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
            }
        else
        {                
            JSMMantenerPersonal.setActionCommand("Abierto");
            JDEscritorio.add(personal);
            Dimension desktopSize = JDEscritorio.getSize();
            Dimension FrameSize = personal.getSize();
            personal.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
            evn.write(JMSesion.getText(), "Abrio el formulario 'Mantener Personal'", "JFPrincipal", "Menu 'Mantener Personal' Presionado");
            personal.show();
        }
    }
    catch (Exception e)
    {

        lc.write("Error intentando abrir 'Mantenimiento Personal'", "JFRPrincipal", e);
    }
        
    }//GEN-LAST:event_JSMMantenerPersonalActionPerformed

    private void JSMMantenerProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JSMMantenerProductoActionPerformed

    try
    {
        JIFMantenerProductos producto = new JIFMantenerProductos();
        JFrame jf=new JFrame();
        jf.setAlwaysOnTop(true);

        if(JSMMantenerProducto.getActionCommand().equals("Abierto"))
            {
                SYSAUDIOCON sysau = new SYSAUDIOCON();
                sysau.E_ERROR();
                JOptionPane.showMessageDialog(jf,"Ya esta abierto", "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
            }
        else
        {                
            JSMMantenerProducto.setActionCommand("Abierto");
            JDEscritorio.add(producto);
            Dimension desktopSize = JDEscritorio.getSize();
            Dimension FrameSize = producto.getSize();
            producto.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
            evn.write(JMSesion.getText(), "Abrio el formulario 'Mantener Producto'", "JFPrincipal", "Menu 'Mantener Producto' Presionado");
            producto.show();
        }
    }
    catch (Exception e)
    {

        lc.write("Error intentando abrir 'Mantenimiento Productos'", "JFRPrincipal", e);
    }

        
    }//GEN-LAST:event_JSMMantenerProductoActionPerformed

    private void JSMMantenerImplementosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JSMMantenerImplementosActionPerformed

    try
    {
        JIFMantenerImplementos producto = new JIFMantenerImplementos();
        JFrame jf=new JFrame();
        jf.setAlwaysOnTop(true);

        if(JSMMantenerImplementos.getActionCommand().equals("Abierto"))
            {
                SYSAUDIOCON sysau = new SYSAUDIOCON();
                sysau.E_ERROR();
                JOptionPane.showMessageDialog(jf,"Ya esta abierto", "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
            }
        else
        {                
            JSMMantenerImplementos.setActionCommand("Abierto");
            JDEscritorio.add(producto);
            Dimension desktopSize = JDEscritorio.getSize();
            Dimension FrameSize = producto.getSize();
            producto.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
            evn.write(JMSesion.getText(), "Abrio el formulario 'Mantener Implementos'", "JFPrincipal", "Menu 'Mantener Implementos' Presionado");
            producto.show();
        }
    }
    catch (Exception e)
    {

        lc.write("Error intentando abrir 'Mantenimiento Implementos'", "JFRPrincipal", e);
    }

    }//GEN-LAST:event_JSMMantenerImplementosActionPerformed

    private void JSMGenerarCotizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JSMGenerarCotizacionActionPerformed
        
    try
    {
        JIFGenerarCotizacion generar_coti = new JIFGenerarCotizacion();
        JFrame jf=new JFrame();
        jf.setAlwaysOnTop(true);

        if(JSMGenerarCotizacion.getActionCommand().equals("Abierto"))
            {
                SYSAUDIOCON sysau = new SYSAUDIOCON();
                sysau.E_ERROR();
                JOptionPane.showMessageDialog(jf,"Ya esta abierto", "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
            }
        else
        {                
            JSMGenerarCotizacion.setActionCommand("Abierto");
            JDEscritorio.add(generar_coti);
            Dimension desktopSize = JDEscritorio.getSize();
            Dimension FrameSize = generar_coti.getSize();
            generar_coti.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
            evn.write(JMSesion.getText(), "Abrio el formulario 'Generar Cotización'", "JFPrincipal", "Menu 'Generar Cotización' Presionado");
            generar_coti.show();
        }
    }
    catch (Exception e)
    {

        lc.write("Error intentando abrir 'Generar Cotización'", "JFRPrincipal", e);
    }     

    }//GEN-LAST:event_JSMGenerarCotizacionActionPerformed

    private void JSMGenerarOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JSMGenerarOrdenActionPerformed

    try
    {
        JIFGenerarOrdenTrabajo orden = new JIFGenerarOrdenTrabajo();
        JFrame jf=new JFrame();
        jf.setAlwaysOnTop(true);

        if(JSMGenerarOrden.getActionCommand().equals("Abierto"))
            {
                SYSAUDIOCON sysau = new SYSAUDIOCON();
                sysau.E_ERROR();
                JOptionPane.showMessageDialog(jf,"Ya esta abierto", "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
            }
        else
        {                
            JSMGenerarOrden.setActionCommand("Abierto");
            JDEscritorio.add(orden);
            Dimension desktopSize = JDEscritorio.getSize();
            Dimension FrameSize = orden.getSize();
            orden.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
            evn.write(JMSesion.getText(), "Abrio el formulario 'Generar Orden Servicio'", "JFPrincipal", "Menu 'Generar Orden Servicio' Presionado");
            orden.show();
        }
    }
    catch (Exception e)
    {

        lc.write("Error intentando abrir 'Generar Orden Servicio'", "JFRPrincipal", e);
    }     

    }//GEN-LAST:event_JSMGenerarOrdenActionPerformed

    private void JSMConsultarOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JSMConsultarOrdenActionPerformed

    try
      {
          JIFConsultarOrdenesTrabajo orden = new JIFConsultarOrdenesTrabajo();
          JFrame jf=new JFrame();
          jf.setAlwaysOnTop(true);

          if(JSMConsultarOrden.getActionCommand().equals("Abierto"))
              {
                  SYSAUDIOCON sysau = new SYSAUDIOCON();
                  sysau.E_ERROR();
                  JOptionPane.showMessageDialog(jf,"Ya esta abierto", "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
              }
          else
          {                
              JSMConsultarOrden.setActionCommand("Abierto");
              JDEscritorio.add(orden);
              Dimension desktopSize = JDEscritorio.getSize();
              Dimension FrameSize = orden.getSize();
              orden.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
              evn.write(JMSesion.getText(), "Abrio el formulario 'Consultar Orden Trabajo'", "JFPrincipal", "Menu 'Consultar Orden Trabajo' Presionado");
              orden.show();
          }
      }
      catch (Exception e)
      {

          lc.write("Error intentando abrir 'Consultar Orden Trabajo'", "JFRPrincipal", e);
      }     

    }//GEN-LAST:event_JSMConsultarOrdenActionPerformed

    //METODOS ESPECIALES DE REGISTRO DE SALIDA
    
    private int CT(int h,int m)
    {
        int HH = h*3600;
        int mm = m*60;
        int t = HH+mm;
        return t;
    }
    
    private String comprt(int CT1,int CT2)
    {
        if(CT1 == CT2)
        {
           return "0";  
        }else
            {
                int result = CT1-CT2;
                return "Ha trabajado : "+(Math.abs(result)/60)+" Minutos "+"("+FMF(Math.abs(result)/60)+" Horas)";
                
            }
    }
    
    private String comprt_salida(int HS,int HSO,int CT1,int CT2)
    {
        
        if(HS == HSO)
        {
            return "NO";
        }else
            if(HS>HSO)
            {
                int result = CT1-CT2;
                
                return "Ha trabajado horas extra : "+hora_extra(Math.abs(result)/60);
            }else
                if(HS<HSO)
                {
                    return "SI";
                }
        return "NULL";
    }
    
    private String hora_extra(int m)
    {
        int HOT = 9;
        int HT = m/60;
        
        if(HOT == HT)
        {
            return "0";
        }else
            if(HT>HOT)
            {
                return ""+(HT-HOT);
            }else
                if(HT<HOT)
                {
                    return "0";
                }
        System.out.println(HT);
        return "NULL";
    }
    
    public String FMF(int minutos) 
    {
        String formato = "%02d:%02d";
        long horasReales = TimeUnit.MINUTES.toHours(minutos);
        long minutosReales = TimeUnit.MINUTES.toMinutes(minutos) - TimeUnit.HOURS.toMinutes(TimeUnit.MINUTES.toHours(minutos));
        return String.format(formato, horasReales, minutosReales);
    }
     
    
    //FIN METODOS ESPECIALES DE REGISTRO DE SALIDA
    
    private void JSMRegistrarSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JSMRegistrarSalidaActionPerformed

    try 
    {
        evn.write(JMSesion.getText(), "Ha registrado su salida", "JFRPrincipal", "Menu 'Registrar Salida' Presionado");
        JFrame jf=new JFrame();
        jf.setAlwaysOnTop(true);
        MWCON mw = new MWCON();
        NANOCON_Asistencia P_ASIST = new NANOCON_Asistencia();

        String ID_PER = P_ASIST.obtenerIDNomCOn(JMSesion.getText());

        String ArrayTemp[] = P_ASIST.obtenerHE(mw.fecha_actual_clasica(), ID_PER).split(":");
        String ArrayTemp2[] = mw.hour_actual().split(":");


        //hs
        int hsH = Integer.parseInt(ArrayTemp2[0]);
        int hsM = Integer.parseInt(ArrayTemp2[1]);

        //int hsH = 20;
        //int hsM = 30;

        //he
        int heH = Integer.parseInt(ArrayTemp[0]);
        int heM = Integer.parseInt(ArrayTemp[1]);

        //hso
        int hso = 17;

        //FORMULA = R= comprt(HORA_SALIDA,HORA_ENTRADA);
        String r = comprt(CT(hsH, hsM), CT(heH, heM));

        System.out.println(r);

        //Salida temprano
        //FORMULA = ST = comprt(HORA SALIDA,HORA SALIDA ORIGINAL,HORAS TRABAJADAS);
        String ST = comprt_salida(hsH,hso,CT(hsH, hsM), CT(heH, heM));
        System.out.println(ST);

        P_ASIST.RegistrarSalida(ID_PER, mw.fecha_actual_clasica());
        P_ASIST.UpdateSalida(ID_PER, mw.fecha_actual_clasica(),r,ST);
        JSMRegistrarSalida.setEnabled(false);
        JSMRegistrarSalida.setText("Salida Registrada");

    } catch (Exception e) 
        {
            lc.write("Ha ocurrido algun error al intentar marcar salida", "CLASE PRINCIPAL -> REGISTRAR SALIDA", e);
        }
        
    }//GEN-LAST:event_JSMRegistrarSalidaActionPerformed

    private void JSMGenerarCertificadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JSMGenerarCertificadoActionPerformed
  
    try
    {
        JIFGenerarCertificado CERT = new JIFGenerarCertificado();
        JFrame jf=new JFrame();
        jf.setAlwaysOnTop(true);

        if(JSMGenerarCertificado.getActionCommand().equals("Abierto"))
            {
                SYSAUDIOCON sysau = new SYSAUDIOCON();
                sysau.E_ERROR();
                JOptionPane.showMessageDialog(jf,"Ya esta abierto", "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
            }
        else
        {                
            JSMGenerarCertificado.setActionCommand("Abierto");
            JDEscritorio.add(CERT);
            Dimension desktopSize = JDEscritorio.getSize();
            Dimension FrameSize = CERT.getSize();
            CERT.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
            evn.write(JMSesion.getText(), "Abrio el formulario 'Generar Certificado'", "JFPrincipal", "Menu 'Generar Certificado' Presionado");
            CERT.show();
        }
    }
    catch (Exception e)
    {

        lc.write("Error intentando abrir 'Generar Orden Servicio'", "JFRPrincipal", e);
    }     

    }//GEN-LAST:event_JSMGenerarCertificadoActionPerformed

    private void JSMConsultarCertificadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JSMConsultarCertificadoActionPerformed

        
    try
      {
          JIFConsultarCertificados cert = new JIFConsultarCertificados();
          JFrame jf=new JFrame();
          jf.setAlwaysOnTop(true);

          if(JSMConsultarCertificado.getActionCommand().equals("Abierto"))
              {
                  SYSAUDIOCON sysau = new SYSAUDIOCON();
                  sysau.E_ERROR();
                  JOptionPane.showMessageDialog(jf,"Ya esta abierto", "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
              }
          else
          {                
              JSMConsultarCertificado.setActionCommand("Abierto");
              JDEscritorio.add(cert);
              Dimension desktopSize = JDEscritorio.getSize();
              Dimension FrameSize = cert.getSize();
              cert.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
              evn.write(JMSesion.getText(), "Abrio el formulario 'Consultar Certificado'", "JFPrincipal", "Menu 'Consultar Certificado' Presionado");
              cert.show();
          }
      }
      catch (Exception e)
      {

          lc.write("Error intentando abrir 'Consultar Certificado'", "JFRPrincipal", e);
      }     
        
        
    }//GEN-LAST:event_JSMConsultarCertificadoActionPerformed

    private void JSMConsultarCertificadoVenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JSMConsultarCertificadoVenActionPerformed
        
    try
      {
          
          JIFConsultarCertificadosVencidos cert = new JIFConsultarCertificadosVencidos();
          JFrame jf=new JFrame();
          jf.setAlwaysOnTop(true);

          if(JSMConsultarCertificadoVen.getActionCommand().equals("Abierto"))
              {
                  SYSAUDIOCON sysau = new SYSAUDIOCON();
                  sysau.E_ERROR();
                  JOptionPane.showMessageDialog(jf,"Ya esta abierto", "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
              }
          else
          {                
              JSMConsultarCertificadoVen.setActionCommand("Abierto");
              JDEscritorio.add(cert);
              Dimension desktopSize = JDEscritorio.getSize();
              Dimension FrameSize = cert.getSize();
              cert.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
              evn.write(JMSesion.getText(), "Abrio el formulario 'Consultar Certificados Vencidos'", "JFPrincipal", "Menu 'Consultar Certificados Vencidos' Presionado");
              cert.show();
          }
      }
      catch (Exception e)
      {

          lc.write("Error intentando abrir 'Consultar Certificados Vencidos'", "JFRPrincipal", e);
      }     
        
    }//GEN-LAST:event_JSMConsultarCertificadoVenActionPerformed

    private void JSMRegistroContactosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JSMRegistroContactosActionPerformed

    try
      {
          JIFRegistroContacto reg = new JIFRegistroContacto();
          JFrame jf=new JFrame();
          jf.setAlwaysOnTop(true);

          if(JSMRegistroContactos.getActionCommand().equals("Abierto"))
              {
                  SYSAUDIOCON sysau = new SYSAUDIOCON();
                  sysau.E_ERROR();
                  JOptionPane.showMessageDialog(jf,"Ya esta abierto", "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
              }
          else
          {                
              JSMRegistroContactos.setActionCommand("Abierto");
              JDEscritorio.add(reg);
              Dimension desktopSize = JDEscritorio.getSize();
              Dimension FrameSize = reg.getSize();
              reg.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
              evn.write(JMSesion.getText(), "Abrio el formulario 'Registro Contactos'", "JFPrincipal", "Menu 'Registro Contactos' Presionado");
              reg.show();
          }
      }
      catch (Exception e)
      {

          lc.write("Error intentando abrir 'Registro Contactos'", "JFRPrincipal", e);
      }    

    }//GEN-LAST:event_JSMRegistroContactosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFRPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFRPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFRPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFRPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new JFRPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane JDEscritorio;
    public static javax.swing.JMenu JMConsultar;
    private javax.swing.JMenu JMGenerar;
    private javax.swing.JMenu JMMantenimientos;
    private javax.swing.JMenuBar JMPrincipal;
    public static javax.swing.JMenu JMSesion;
    private javax.swing.JMenu JMVentas;
    private javax.swing.JMenuItem JSMCerrarSesion;
    public static javax.swing.JMenuItem JSMConsultarCertificado;
    public static javax.swing.JMenuItem JSMConsultarCertificadoVen;
    public static javax.swing.JMenuItem JSMConsultarOrden;
    public static javax.swing.JMenuItem JSMGenerarCertificado;
    public static javax.swing.JMenuItem JSMGenerarCotizacion;
    public static javax.swing.JMenuItem JSMGenerarOrden;
    public static javax.swing.JMenuItem JSMMantenerClientes;
    public static javax.swing.JMenuItem JSMMantenerImplementos;
    public static javax.swing.JMenuItem JSMMantenerPersonal;
    public static javax.swing.JMenuItem JSMMantenerProducto;
    public static javax.swing.JMenuItem JSMMantenimientoUsuarios;
    public static javax.swing.JMenuItem JSMPermisosUsuarios;
    public static javax.swing.JMenuItem JSMRegistrarSalida;
    public static javax.swing.JMenuItem JSMRegistroContactos;
    private javax.swing.JToolBar JTBHerramientas;
    private javax.swing.JButton btnAdministrarCertificado;
    private javax.swing.JButton btnAgregarCliente;
    private javax.swing.JButton btnAgregarPersonal;
    private javax.swing.JButton btnGenerarOrden;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JMenu jMenu4;
    // End of variables declaration//GEN-END:variables
}
